### ISSUE TITLE
Does not compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by bmartin427** [lstalmir/VulkanProfiler#22]
The first issue I ran into is the use of VC++ proprietary `__forceinline` keyword, which is not supported with GCC.  But even after defining `__forceinline="__attribute__((always_inline))"`, I get a number of other compile errors as well: bad casting syntax, bad template instantiations, `<vector>` not included, use of VC++ proprietary `_strdup` function, etc.

**Comment by lstalmir** [comment]
Thank you for opening this issue. I must admit that I haven't looked at the Linux' part of the code for some time, so it must have broken after a few changes which were tested only on Windows.

I looked into the code and fixed all the issues I found, including the ones you mentioned. The current master branch compiles with GCC and successfully attaches to Sascha Willems' samples on 22.04, but it also should work on 20.04.
